wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("new", views.new, name="new"),
    path("edit", views.edit, name="edit"),
    path("re_new", views.re_new, name="re_new"),
    path("random_page", views.random_page, name="random_page"),
    path("<str:word>", views.title, name="title")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render

from . import util

from random import choice


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def search(request):
    if request.method == "POST":
        word = (request.POST)['q']
        txt = util.get_entry(word)
        if txt is not None:
            return render(request, "encyclopedia/title.html", {
                "title": word,
                "body": util.convert(txt)
            })
        else:
            substr = util.entry_substr(word)
            if len(substr) < 1:
                empty = f"Your search -{word}- nid not match any document"
                return render(request, "encyclopedia/error.html", {
                    "title": f"Search Results for {word}",
                    "body": empty
                })

            else:
                result = (substr)
                return render(request, "encyclopedia/search.html", {
                    "keyword": word,
                    "text": result
                })


def new(request):
    if request.method == "POST":
        title = (request.POST)['title']
        content = (request.POST)['content']
        if not title or not content:
            return render(request, "encyclopedia/error.html", {
                "title": "Invalid Entry",
                "body": ('<h1 style="margin-top: 250px; text-align: center; font-size: 500%;"> <b>Invalid Entry </b></h1>')
            })
        else:
            exist = util.check(title)
            if exist == 1:
                return render(request, "encyclopedia/error.html", {
                    "title": "Already Exists",
                    "body": ('<h1 style="margin-top: 250px; text-align: center; font-size: 500%;"> <b>404: The entry already exists</b></h1>')
                })
            else:
                try:
                    util.save_entry(title, content)
                    txt = util.get_entry(title)
                    return render(request, "encyclopedia/title.html", {
                        "title": title,
                        "body": util.convert(txt)
                    })
                except:
                    return render(request, "encyclopedia/error.html", {
                        "title": "503 Service Unavailable",
                        "body": ('<h1 style="margin-top: 250px; text-align: center; font-size: 500%;"> <b>404: 503 Service Unavailable:Error has occurred </b></h1>')
                    })
    else:
        return render(request, "encyclopedia/new_page.html")

def edit(request):
    if request.method == "POST":
        title = (request.POST)['title']
        txt = util.get_entry(title)
        if txt is not None:
            return render(request, "encyclopedia/edit.html", {
                "title": title,
                "body": txt
            })
        else:
            return render(request, "encyclopedia/error.html", {
                        "title": "503 Service Unavailable",
                        "body": ('<h1 style="margin-top: 250px; text-align: center; font-size: 500%;"> <b>404: 503 Service Unavailable:Error has occurred </b></h1>')
                    })


def re_new(request):
    if request.method == "POST":
        title = (request.POST)['title']
        content = (request.POST)['content']
        if not title or not content:
            return render(request, "encyclopedia/error.html", {
                "title": "Invalid Entry",
                "body": ('<h1 style="margin-top: 250px; text-align: center; font-size: 500%;"> <b>Invalid Entry </b></h1>')
            })
        else:
                try:
                    util.save_entry(title, content)
                    txt = util.get_entry(title)
                    return render(request, "encyclopedia/title.html", {
                        "title": title,
                        "body": util.convert(txt)
                    })
                except:
                    return render(request, "encyclopedia/error.html", {
                        "title": "503 Service Unavailable",
                        "body": ('<h1 style="margin-top: 250px; text-align: center; font-size: 500%;"> <b>404: 503 Service Unavailable:Error has occurred </b></h1>')
                    })
    return render(request, "encyclopedia/error.html", {
                        "title": "503 Service Unavailable",
                        "body": ('<h1 style="margin-top: 250px; text-align: center; font-size: 500%;"> <b>404: 503 Service Unavailable:Error has occurred </b></h1>')
                    })


def random_page(request):
    list = util.list_entries()
    title = choice(list)
    txt = util.get_entry(title)
    return render(request, "encyclopedia/title.html", {
            "title": title,
            "body": util.convert(txt)
        })


def title(request, word):
    txt = util.get_entry(word)
    if txt is None:
        return render(request, "encyclopedia/error.html", {
            "title": "404 page not found",
            "body": ('<h1 style="margin-top: 250px; text-align: center; font-size: 500%;"> <b>404: page not found</b></h1>')
        })
    else:
        return render(request, "encyclopedia/title.html", {
            "title": word,
            "body": util.convert(txt)
        })

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}

<h2 style="margin-top: 20px; margin-bottom: 20px; text-align: left; font-size: 150%;">Create a new page</h2>
<form action="{% url 'encyclopedia:re_new' %}" method="post">
    {% csrf_token %}
    <input  style="width: 200px; height: 44px; text-indent: 5px; margin-bottom: 20px;" type="text" name="title" placeholder="Title:" value="{{title}}"><br>
    <textarea style="width: 800px; height: 400px; text-indent: 5px; margin-bottom: 20px;" name="content" rows="4" cols="50" placeholder="Content:">{{body}}</textarea><br>
    <button type="submit" style="background-color: #4CAF50; border: none; color: #3c4043;height: 36px;
    min-width: 54px; text-align: center; border: 1px solid #f8f9fa; border-radius: 4px; font-family: arial,sans-serif;">Submit</button>
</form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
{% autoescape off %}{{ body }}{% endautoescape %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href="{% url 'encyclopedia:title' word=entry %}" style="text-decoration: none; color: #000;" >{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}" style="text-decoration: none; color: #000;">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}" style="text-decoration: none; color: #000;">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}" style="text-decoration: none; color: #000;" >Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

<h2 style="margin-top: 20px; margin-bottom: 20px; text-align: left; font-size: 150%;">Create a new page</h2>
<form action="{% url 'encyclopedia:new' %}" method="post">
    {% csrf_token %}
    <input  style="width: 200px; height: 44px; text-indent: 5px; margin-bottom: 20px;" type="text" name="title" placeholder="Title:"><br>
    <textarea style="width: 800px; height: 400px; text-indent: 5px; margin-bottom: 20px;" name="content" rows="4" cols="50" placeholder="Content:"></textarea><br>
    <button type="submit" style="background-color: #008CBA; border: none; color: #3c4043;
    height: 36px; min-width: 54px; text-align: center; border: 1px solid #f8f9fa; border-radius: 4px; font-family: arial,sans-serif;">Submit</button>
</form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
<h1>Search Results for {{keyword}} </h1>

    <ul>
        {% for entry in text %}
            <li> <a href="{% url 'encyclopedia:title' word=entry %}" style="text-decoration: none; color: #000;" >{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
{% autoescape off %}{{ body }}{% endautoescape %}
<form action="{% url 'encyclopedia:edit' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="title" value="{{title}}">
    <button type="submit" style="margin-top: 20px; border: none; background-color: #f44336; color: #3c4043; height: 36px;
    min-width: 54px; text-align: center; border: 1px solid #f8f9fa; border-radius: 4px; font-family: arial,sans-serif;">Edit</button>
</form>
{% endblock %}